config/routes.rb
CarTracker::Application.routes.draw do
  root to: 'cars#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :cars do
      resources :reservations
      resources :notifications
  end
  resources :drivers, except:[:destroy] do
    resources :reservations
    resources :notifications
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :reservations
  has_many :notifications
  has_many :notify_drivers, through: :notifications, source: :driver
  has_many :reserve_drivers, through: :reservations, source: :driver
  validates :make,:model, presence: true, length:{maximum:11}
  validates :year, presence: true, numericality: {only_integer: true}

  def current_reservation
    self.reservations.each do |reservation|
      if (reservation.reserved_from..reservation.reserved_to).cover?(Time.zone.now.utc)
        return reservation
      end
    end
    return
  end

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :reservations
  has_many :notifications
  has_many :notify_cars, through: :notifications, source: :car
  has_many :reserve_cars, through: :reservations, source: :car
  validates :name, presence: true
  validates :password, presence: true, on: :create
  has_secure_password validations: false

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
belongs_to :car
belongs_to :driver
validate :return_before_pickup_time, :conflict
validates :reserved_from, :reserved_to, presence: true
before_save :delete_old_reservations

  def return_before_pickup_time
    if self.reserved_to < self.reserved_from
      errors.add(:time, "Return date/time cannot be before Pickup date/time")
    end
  end

  def conflict
    Reservation.where("car_id = #{self.car_id}").each_with_index do |existing,index|
      if (self.reserved_from - existing.reserved_to)*(existing.reserved_from-self.reserved_to)>= 0
        errors.add(:time, "Schedule conflict: #{existing.driver.name} from: #{existing.reserved_from} to: #{existing.reserved_to}")
      end
    end
  end

  def delete_old_reservations
    Reservation.where("reserved_to < ?", Time.zone.now).destroy_all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user 
    session[:user]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to login_path
    end
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :require_user
  
  def index
    @cars = Car.all
    @reservation = Reservation.new
    @notification = Notification.new
    render :index
  end

  def show

  end

  def new
    @car = Car.new

  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = "New Vehicle Created"
      redirect_to root_path
    else
      render 'new'
    end

  end

  def edit
    @car = Car.find(params[:id])

  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      flash[:notice]="Successful Update"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @car = Car.find(params[:id]).destroy
    flash[:notice] = "Vehicle Deleted"
    redirect_to root_path


  end

  private
  def car_params
      params.require(:car).permit!
  end

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

  def edit
    @current_user = current_user
  end

  def update
    @current_user = Driver.find(params[:id])
    if @current_user.update(driver_params)
      flash[:notice] = "User Updated"
      redirect_to root_path
    else
      render 'edit'
    end

  end

  private
  def driver_params
    params.require(:driver).permit!
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :require_user

  def create
    @cars = Car.all
    time = params[:reservation]
    @date_format_error = false
    if !valid_date?(time[:reserved_from]) || !valid_date?(time[:reserved_to])
      @reservation = Reservation.new(car_id: params[:car_id], driver_id: params[:driver_id])
      @reservation.errors.add(:time, "Date format error")
      render "cars/index"
      return
    end
    @start = Time.strptime(time[:reserved_from],'%m/%d/%Y %I:%M %p')
    @end = Time.strptime(time[:reserved_to],'%m/%d/%Y %I:%M %p')
    @reservation = Reservation.new(reserved_from: @start, reserved_to: @end, car_id: params[:car_id], driver_id:current_user.id )
    if @reservation.save
      flash[:notice] = "You have successfully reserved the vehicle"  
      redirect_to root_path
    else
      flash.now[:error] = "There were errors"
      render "cars/index"
    end
  end

  def destroy
    current_reservation = Car.find(params[:car_id]).current_reservation
    if current_reservation && current_user === current_reservation.driver
      current_reservation.delete
      #you would send out texts here
      Car.find(params[:car_id]).notifications.destroy_all
      flash[:notice] = "Car returned"
      redirect_to :back
    else
      flash[:error] = "You can't delete a reservation that isn't yours"
      redirect_to :back
    end
  end

  private

  def valid_date?(str)
    /^\d{1,2}\/\d{1,2}\/\d{4} \d{1,2}:\d{2} (AM|PM)$/ =~ str
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    username = params[:user]
    password = params[:password]
    user = Driver.find_by(name: username)
    if Driver.exists?(name: username) && user.authenticate(params[:password])
      session[:user] = user
      flash[:notice] = "Welcome, #{user.name}!"
      redirect_to root_path
    else
      flash[:error] = "Incorrect username/password"
      redirect_to :back
    end
  end

  def destroy
    session[:user] = nil
    flash[:notice] = "Logged out!"
    redirect_to '/login'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/cars/edit.html.erb
<%= render 'shared/header' %>
<%= render 'shared/errors' %>
<div class="col-md-3 col-md-offset-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
    New Vehicle
    </div>
    <div class="panel-body text-center">
      <%= render 'shared/obj_errors', obj: @car %>
      <%= form_for @car, class:"form-inline" do |f| %>
        <div class="form-group">
          <%= f.label :year %><br>
          <%= f.text_field :year %>
        </div>
        <div class="form-group">
          <%= f.label :make %><br>
          <%= f.text_field :make %>
        </div>
        <div class="form-group">
          <%= f.label :model %><br>
          <%= f.text_field :model %>
        </div>
        <%= f.submit class:"btn btn-success" %>
        <% end %>
       <br>
      <%= form_for @car, method:"delete", class:"form-inline" do |f| %>
        <%= f.submit "Delete", class:"btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/errors' %>
<div class = "navbar-form">
  <% @cars.each do |car| %>
    <div class="col-md-4">
      <div class= "panel panel-primary">
        <div class="panel-heading">
          <h5 class="panel-title-front-page">
            <%= "'#{car.year.to_s[2,3]} #{car.make} #{car.model}" %>
          </h5>
          <div class="current_status_label">
            <% if car.current_reservation %>
              <span class="label label-warning"><%= "#{car.current_reservation.driver.name} #{car.current_reservation.reserved_from.strftime("%H:%M")}-#{car.current_reservation.reserved_to.strftime("%H:%M")}" %></span>
            <% else %>
              <span class="label label-success" ><%= "AVAILABLE" %></span>
            <% end %>
          </div>
        </div>
      <div class="panel-body-front-page<%='-time-error' if car===@reservation.car && @reservation.errors %>">
        <% if car === @reservation.car %>
          <%= render 'reservations/reservation_errors', reservation:@reservation, date_error: @date_format_error %>
        <% end %>
        <%= form_for([car, @reservation],html:{class:"navbar-form"}) do |f|%>
          <div class="form-group">
            <%= f.label :reserve_from %>
            <div class='col-med-2'>
            <div class='input-group date reservation_time_field'>
              <%= f.text_field :reserved_from, class:'form-control' %>
              <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
            </div>
            <%= f.label :reserve_to %>
            <div class='col-med-2'>
              <div class='input-group date reservation_time_field'>
                <%= f.text_field :reserved_to, class:'form-control' %>
              <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
              </span>
              </div>
            </div>
                <br>
                <%= f.submit "Confirm", class:'btn btn-success' %>
                <% end %>
          </div>
      </div>
      <div class = "panel-footer">
        <button class= "btn btn-primary reservation-list-btn" type="button"> Reservations <span class="badge total-badge" id="car-<%= car.id %>-badge"><%= "#{car.reservations.size}" %></span></button>
        <% if car.current_reservation && current_user.id === car.current_reservation.driver.id %>
          <%= form_for [car,car.current_reservation],method:"delete" do |f| %>
          <%= f.submit "Check Vehicle In", class:"btn btn-warning pull-right" %>
          <% end %>
        <% else %>
          <button class= "expand-reserve btn btn-success pull-right" type="button">Make Reservation</button><br>
        <% end %>
        <% if car.current_reservation && current_user.id != car.current_reservation.driver.id %>
          <%= form_for [car, @notification], remote:true , method:"post",html:{class:"notify"} do |f| %>
          <div class="form-group">

            <%= f.check_box(:car_id, {class:"notify-checkbox"}, car.id , nil)  %>
            <%= f.label "Text me if vehicle is returned early" %>
            </div>
          <% end %>
         
        <% end %>
        <div class="reservation_list">
          <table class="table table-striped table-condensed reservation-table" id="car-<%= car.id %>-reservations">
            <tr><th>Name</th><th>From</th><th>To</th></tr>
          <tr>
            <% car.reservations.each do |reservation| %> 
              <td><%="  #{reservation.driver.name}  " %></td>
              <td><%= " #{reservation.reserved_from.strftime('%m/%d/%Y %I:%M %p')} " %> </td>
              <td><%= " #{reservation.reserved_to.strftime('%m/%d/%Y %I:%M %p')} " %></td>
          </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/cars/new.html.erb
<%= render 'shared/header' %>
<%= render 'shared/errors' %>
<div class="col-md-3 col-md-offset-4">
<div class="panel panel-primary">
  <div class="panel-heading">
    New Vehicle
    </div>
      <div class="panel-body text-center">
      <%= render 'shared/obj_errors', obj: @car %>
    <%= form_for @car, class:"form-horizontal input-large" do |f| %>
    <div class="form-group">
       <%= f.label :year %><br>
      <%= f.text_field :year %>
    </div>
     <div class="form-group">
      <%= f.label :make %><br>
      <%= f.text_field :make %>
      </div>
       <div class="form-group">
       <%= f.label :model %><br>
      <%= f.text_field :model %>
      </div>
      <%= f.submit class:'btn btn-success' %>
       <% end %>
      </div>
   
    </div>
</div>

app/views/drivers/edit.html.erb
<%= render 'shared/header' %>
<%= render 'shared/errors' %>
<div class="col-md-7 col-md-offset-2">
<div class="panel panel-primary">
  <div class="panel-heading">
    Update Profile
    </div>
      <div class="panel-body">
      <%= render 'shared/obj_errors', obj: @current_user %>
    <%= form_for @current_user do |f| %>
  
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Update" %>

    <% end %>
    </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_reservation_errors.html.erb
  <% if reservation.errors %>
    <div class="alert alert-danger" role="alert">
      <% reservation.errors.full_messages.each do |message|%>
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <%= message %><br>
        <% end %>
    </div>
<% end %>

app/views/shared/_errors.html.erb
  
  <% if flash[:error] %>
    <div class="alert alert-danger text-center">
      <%= flash[:error] %>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success text-center">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <br>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href=<%= root_path %>>GovieVan!</a>
    </div>
    <% if logged_in? %>
    <p class="navbar-text"><%= "Welcome, #{current_user.name}" %></p>
    <ul class="nav navbar-nav">
      <li><a href=<%= edit_driver_path(current_user) %>>Edit Profile</a>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add/Edit Vehicle<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Car.all.each do |car| %>
            <li><a href= <%= edit_car_path(car) %> > <%= "#{car.year} #{car.make} #{car.model}" %>
            </a></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href=<%= new_car_path %> >Add New Vehicle</a></li>
          </ul>
        </li>
      <li><a href="/logout">Log Out</a></li>
      </ul>
    </div>
    <% end %>
  </div>
</nav>

app/views/shared/_obj_errors.html.erb
  <% if !obj.errors.empty? %>
      <div class="alert alert-danger" role="alert">
      <% obj.errors.full_messages.each do |message|%>
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <%= message %><br>
        <% end %>
      </div>
<% end %>